// Auto-generated by Alejandro Navarro Ayala's QA Automation Supervisor
// This script ensures all required router and E2E test files exist.
const fs = require('fs');
const path = require('path');

console.log('[QA] Iniciando verificación de entorno...');

// ------ CONFIGURACIÓN ----- //
const routersToEnsure = ['producersRouter', 'batchesRouter', 'eventsRouter', 'authRouter'];
const routesPath = 'apps/api/src/presentation/routes/';
const e2eTestsPath = 'apps/api/tests/e2e/';
const appEntry = 'apps/api/src/presentation/routes/index.ts';

// ------ 1. Validar y crear Routers ------ //
routersToEnsure.forEach((router) => {
  const routerFile = path.join(routesPath, `${router}.ts`.replace('Router', '.routes'));
  if (!fs.existsSync(routerFile)) {
    const factoryName = `create${router.charAt(0).toUpperCase() + router.slice(1)}`;
    const useCaseName = `${router.charAt(0).toUpperCase() + router.slice(1).replace('Router', 'UseCases')}`;
    const routerCode = `
import { Router } from 'express';
import { ${useCaseName} } from '../../application/use-cases/${router.replace('Router', '')}';

export function ${factoryName}(useCases: ${useCaseName}) {
  const router = Router();
  // TODO: Define endpoints here
  router.get('/', (req, res) => res.status(200).json({ message: '${routerName} OK' }));
  return router;
}
`;
    fs.mkdirSync(routesPath, { recursive: true });
    fs.writeFileSync(routerFile, routerCode.trim(), 'utf8');
    console.log(`[QA] Archivo de router CREADO: ${routerFile}`);
  } else {
    console.log(`[QA] Archivo de router ya existe: ${routerFile}`);
  }
});

// ------ 2. Validar y crear E2E Tests ------ //
if (!fs.existsSync(e2eTestsPath)) fs.mkdirSync(e2eTestsPath, { recursive: true });
routersToEnsure.forEach((router) => {
  const shortName = router.replace('Router', '');
  const file = path.join(e2eTestsPath, `${shortName}.e2e.test.ts`);
  if (!fs.existsSync(file)) {
    const minimumE2E = `
import { describe, it, expect } from 'vitest';
describe('${router}', () => {
  it('should have a placeholder test', () => {
    expect(true).toBe(true);
  });
});
`;
    fs.writeFileSync(file, minimumE2E.trim(), 'utf8');
    console.log(`[QA] Archivo de test E2E CREADO: ${file}`);
  } else {
    console.log(`[QA] Archivo de test E2E ya existe: ${file}`);
  }
});

console.log('[QA] Verificación de entorno completada.');
