import { Worker } from 'bullmq';
import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

const connection = {
  host: process.env.REDIS_HOST || 'localhost',
  port: parseInt(process.env.REDIS_PORT || '6379', 10),
};

console.log('PDF Worker is running...');

const worker = new Worker('pdf-generation', async job => {
  const { data } = job;
  console.log(`Generating PDF for data:`, data);

  const doc = new PDFDocument();
  const filePath = path.join(__dirname, `../generated-pdfs/report-${job.id}.pdf`);

  // Ensure directory exists
  fs.mkdirSync(path.dirname(filePath), { recursive: true });

  doc.pipe(fs.createWriteStream(filePath));

  doc.fontSize(25).text('Product Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(16).text(`Product ID: ${data.productId}`);
  doc.text(`Product Name: ${data.productName}`);
  doc.moveDown();
  doc.text('This is a sample report generated by a background worker.');

  doc.end();

  console.log(`PDF generated at ${filePath}`);
  return filePath;
}, { connection });

worker.on('completed', job => {
  console.log(`Job ${job.id} has completed!`);
});

worker.on('failed', (job, err) => {
  console.log(`Job ${job?.id} has failed with ${err.message}`);
});
