/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProducerCertification,
  IProducerCertificationInterface,
} from "../../../contracts/interfaces/IProducerCertification";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "producerAddress",
        type: "address",
      },
    ],
    name: "isProducerCertified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProducerCertification__factory {
  static readonly abi = _abi;
  static createInterface(): IProducerCertificationInterface {
    return new Interface(_abi) as IProducerCertificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProducerCertification {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IProducerCertification;
  }
}
